rssd add-feed "Alex Demos Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCzUHWB8sRYZ8bNlaxCA4mcA
rssd add-feed "AXIA Futures Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCzFA5mCxXHSCCGxsDBSuRRw
rssd add-feed "Bitcoin Trading Challenge Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UC-dLWl8etTtPSGdbbcYffGw
rssd add-feed "Bookmap Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UC3HKlZ_7gxRgef9SCxu54Lw
rssd add-feed "Brett Steenbarger Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCuF2Y4qPTnFwjzHbUNcaq1w
rssd add-feed "Chat with Traders Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCdnzT5Tl6pAkATOiDsPhqcg
rssd add-feed "Christian Antony Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCrBE3T_vQzZgevVycQIROEg
rssd add-feed "CME Group Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCLC4PuFlyKwK03Sc29YLEGQ
rssd add-feed "Convergent Trading Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCsVnusn4X3w0wXzlwzVNHcQ
rssd add-feed "Day Trading Pro Transformation Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UC834DgaeNkYiJFp2NOiDe9w
rssd add-feed "DeCarley Trading Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCL8YLgChYXiQaxDyGe_svEg
rssd add-feed "easy emini trade Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCbZ7G5UQ69rUe31iJTPSYLQ
rssd add-feed "Edge Traging Group Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCw8Lt5anmErQRd1nZdNZ-uA
rssd add-feed "Eli Buyko - Futures Options Trading Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCeGvkP8bCMCYxnIJb-rvc_g
rssd add-feed "Emini Os Futures Trader Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UClNfsCI0HeHKAwo3vcAUlew
rssd add-feed "Emoji Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCMcm-Y8ldus0kuxvZxEZiDg
rssd add-feed "Fat Cat Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UC9kVkLPTdjaj4shvCFfoA9g
rssd add-feed "FT71 Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCvG6WEPWwfx8ZDr52_hdVFA
rssd add-feed "Futures.io Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCWzHsd2fbLueDSfRunb1DmA
rssd add-feed "IB-Trader Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCrPrYiQrLowsfDRGaco8plQ
rssd add-feed "Interactive Brokers Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCbY1hA0wpRcbyjBLxI-dxvQ
rssd add-feed "James Dalton Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UChqAOLXsMlP4teTeotQ-ynQ
rssd add-feed "Jigsaw Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCEHjJdrOFvgPbmKLECrTqiw
rssd add-feed "Linda Raschke Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCrfW_zlT-ZiCbmj2oNK-shA
rssd add-feed "Marketdelta Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCLdZZPcnxZLB_G7bzG8ZM7A
rssd add-feed "Momentum Trading Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCT56J1q9Qaeqh374yFRZhGQ
rssd add-feed "No BS Trading Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCW-m-lEeboc7OQ8pNTuWpBg
rssd add-feed "Optimus Futures Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCvcSMynnOgjPrhk4GY5dFzw
rssd add-feed "Option Alpha Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCQAvjhqp559qSQx2dcg9WVg
rssd add-feed "Options4Winners Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCEqQKkGGaTMWtOD9SDeM36Q
rssd add-feed "Optionsuniversum Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCxC8_fDHeRR75LJrjZKZTzg
rssd add-feed "Orderflows - Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCI37HXPO1f4o9j4SA83-Iog
rssd add-feed "Peter Becker Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCGfXRi5aG8TIy1Kcmi2h10Q
rssd add-feed "Price Action Order Flow Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCfTf7NJsGKh8U-4svZfz1zA
rssd add-feed "Price Action Volume Trader Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCM5fqsO2h75yrbKpYDLjR0Q
rssd add-feed "PriceSquawk Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCbguel95IpWNysvQpgAgrgw
rssd add-feed "Rohstoff und Futures Trading Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCOjVSjflbqYgMOK_DXpmvBg
rssd add-feed "Scalp Trading Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCyAngszORvKDNe3_4daPIUA
rssd add-feed "ScalpTrader - Youtube Videos" https://www.youtube.com/feeds/videos.xml?channel_id=UC_S-zkBeMO2ubZNRt5jqOTA
rssd add-feed "Slingshot Futures Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCUw5rFGz-vj9ZONcv3JISkg
rssd add-feed "Suricate Trading Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCl0nSqiiixKmnfbztLLsZvg
rssd add-feed "tastytrade Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCLJiSMXJ9K-1AOTqIqdXJgQ
rssd add-feed "Topstep Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCTDYMpdFhZU6Ivf3F2AEVUQ
rssd add-feed "Trade your Plan Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCY4B7RDujdd45zAciISyoFg
rssd add-feed "Trader Dale Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UC1_SoqTCXaM8kk0SxkAyhcQ
rssd add-feed "Trader Ticino Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UC6Hp96HikXwIYJ0Hl8rOk9A
rssd add-feed "Tradestation Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCkgawWP6JCrYhTARr8dXoIw
rssd add-feed "Trading with Guy Bower Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UChkvQ8o3hHO_0v94_bKOt-g
rssd add-feed "TTWTrader Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCzLATAVds1yFBe-vS6D4Taw
rssd add-feed "Van Tharp Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCIq1KpIMe0SBnajIaWv89aw
rssd add-feed "Verillo Trading Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCz4hZwlhjYM3DQTxVfukAeA
rssd add-feed "verniman1 Youtube Channel" https://www.youtube.com/feeds/videos.xml?channel_id=UCvgqCzgJwsj-yTewnudZTZw
